# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Serverless & React on AWS
email: o2oprotocol101@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Full-stack Apps using Serverless and React on AWS.
baseurl: "/s3-bnb-serverless" # the subpath of your site, e.g. /blog
url: "s3-bnb.s3-website-us-east-1.amazonaws.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: smartbiz
github_username:  o2oprotocol

github_repo: "https://github.com/o2oprotocol/s3-bnb-serverless.git"
chatbot_url: "https://m.me/o2oprotocol"
google_analytics: "UA-116921051-1"

collections:
  chapters:
    output: true

# Build settings
markdown: kramdown
#theme: minima
pluginss:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
exclude:
  - Session.vim
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Front Matter defaults
defaults:
  - scope:
      path: ""
    values:
      image: /s3-bnb-serverless/assets/O2O.png
# theme: jekyll-theme-hacker